# Generated by Django 2.0.1 on 2018-07-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20180731_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='appartenir',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
