# Generated by Django 2.0.1 on 2018-08-07 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20180807_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
