# Generated by Django 2.0.1 on 2018-08-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20180807_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='created_by',
        ),
        migrations.AddField(
            model_name='appartenir',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
