# Generated by Django 2.0.1 on 2018-08-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_groupe_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='created_by',
        ),
    ]
