# Generated by Django 2.0.1 on 2018-08-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20180818_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
