# Generated by Django 2.0.1 on 2018-08-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_groupe_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
