# Generated by Django 2.0.1 on 2018-07-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Etudiant',
        ),
    ]
