# Generated by Django 2.0.1 on 2018-08-11 22:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_etudiant'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence', models.CharField(blank=True, max_length=20)),
                ('matricule', models.CharField(blank=True, max_length=15)),
                ('entree', models.DateField(blank=True, default=datetime.date.today)),
                ('faculte', models.CharField(blank=True, max_length=50)),
                ('diplome', models.CharField(blank=True, max_length=30)),
                ('entreprise', models.CharField(blank=True, max_length=20)),
                ('fonction', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='entree',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
