# Generated by Django 2.0.1 on 2018-08-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telephone',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
