# Generated by Django 2.0.1 on 2018-07-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualite',
            name='image_illustration',
        ),
        migrations.RemoveField(
            model_name='actualite',
            name='texte_de_description',
        ),
        migrations.RemoveField(
            model_name='actualite',
            name='titre',
        ),
        migrations.AddField(
            model_name='actualite',
            name='author',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actualite',
            name='image_desciption',
            field=models.ImageField(default=1, upload_to='actuality_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actualite',
            name='text_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='actualite',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
