# Generated by Django 2.0.1 on 2018-07-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180724_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenement',
            old_name='heure_evenement',
            new_name='heure_debut',
        ),
        migrations.AddField(
            model_name='evenement',
            name='heure_fin',
            field=models.TimeField(auto_now=True),
        ),
    ]
