# Generated by Django 2.0.1 on 2018-08-07 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180807_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evenement',
            options={'ordering': ['-date_evenement']},
        ),
    ]
