# Generated by Django 2.0.1 on 2018-08-07 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180807_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date_evenement',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='heure_debut',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='heure_fin',
            field=models.TimeField(),
        ),
    ]
