# Generated by Django 2.0.1 on 2018-08-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180807_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evenement',
            options={'ordering': ('-date_evenement',)},
        ),
    ]
