# Generated by Django 2.0.1 on 2018-08-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20180810_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='time',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
