# Generated by Django 2.0.1 on 2018-08-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20180818_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='mode_payement',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
