# Generated by Django 2.0.1 on 2018-07-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_etudiant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mot_de_passe', models.CharField(max_length=20)),
                ('residence', models.CharField(blank=True, max_length=20)),
                ('matricule', models.CharField(blank=True, max_length=15)),
                ('entree', models.DateField(auto_now_add=True, null=True)),
                ('faculte', models.CharField(blank=True, max_length=50)),
                ('diplome', models.CharField(blank=True, max_length=30)),
                ('entreprise', models.CharField(blank=True, max_length=20)),
                ('fonction', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
