# Generated by Django 2.0.1 on 2018-07-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180627_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mot_de_passe1', models.CharField(max_length=20)),
                ('mot_de_passe2', models.CharField(max_length=20)),
                ('residence', models.CharField(max_length=20)),
                ('matricule', models.CharField(max_length=10)),
                ('faculte', models.CharField(max_length=50)),
                ('diplome', models.CharField(max_length=30)),
                ('entreprise', models.CharField(max_length=20)),
                ('annee_diplome', models.IntegerField()),
                ('fonction', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
