# Generated by Django 2.0.1 on 2018-07-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180710_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='annee_diplome',
            new_name='annee_entree',
        ),
        migrations.RenameField(
            model_name='frequenter',
            old_name='annee_obtention',
            new_name='annee_sortie',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='annee_sortie',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frequenter',
            name='annee_entree',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
