# Generated by Django 2.0.1 on 2018-07-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180724_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='annee_entree',
            field=models.DateField(blank=True),
        ),
    ]
