# Generated by Django 2.0.1 on 2018-07-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20180725_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='annee_entree',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
