# Generated by Django 2.0.1 on 2018-07-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180725_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequenter',
            name='annee_sortie',
        ),
    ]
