# Generated by Django 2.0.1 on 2018-07-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180712_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actualite',
            old_name='image_desciption',
            new_name='image_description',
        ),
    ]
