# Generated by Django 2.0.1 on 2018-07-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180717_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='heure_evenement',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date_evenement',
            field=models.DateField(),
        ),
    ]
