# Generated by Django 2.0.1 on 2018-07-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180717_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='heure_evenement',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date_evenement',
            field=models.DateField(auto_now=True),
        ),
    ]
