# Generated by Django 2.0.1 on 2018-07-27 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180725_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('text', models.TextField()),
                ('add_at', models.DateTimeField(auto_now=True)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Actualite')),
            ],
        ),
    ]
