# Generated by Django 2.0.1 on 2018-07-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180717_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='heure_evenement',
            field=models.TimeField(auto_now=True),
        ),
    ]
