# Generated by Django 2.0.1 on 2018-07-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180717_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='heure_evenement',
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date_evenement',
            field=models.DateTimeField(),
        ),
    ]
