# Generated by Django 2.0.1 on 2018-08-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_actualite_nb_vues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='nb_vues',
            field=models.IntegerField(blank=True),
        ),
    ]
