# Generated by Django 2.0.1 on 2018-08-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180807_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='heure_debut',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='heure_fin',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
