# Generated by Django 2.0.1 on 2018-08-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180807_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evenement',
            options={},
        ),
    ]
