# Generated by Django 2.0.1 on 2018-08-09 20:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0016_auto_20180808_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField(blank=True, default=datetime.date.today)),
                ('time', models.IntegerField(blank=True)),
                ('execute', models.CharField(max_length=30)),
                ('montant', models.IntegerField(default=1000000)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('add_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='evenement',
            options={'ordering': ('date_evenement',)},
        ),
    ]
