# Generated by Django 2.0.1 on 2018-08-10 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0018_auto_20180810_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='add_by',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='montant',
            field=models.IntegerField(blank=True, default=1000000),
        ),
    ]
