# Generated by Django 2.0.1 on 2018-08-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20180810_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='activated',
            new_name='confirmed',
        ),
    ]
