# Generated by Django 2.0.1 on 2018-08-11 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_inscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='alumni',
        ),
    ]
