# Generated by Django 2.0.1 on 2018-08-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_inscription_alumni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='montant',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='time',
            field=models.IntegerField(blank=True),
        ),
    ]
