# Generated by Django 2.0.1 on 2018-08-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_contribution_mode_payement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='date_evenement',
            field=models.DateField(),
        ),
    ]
